home_application/urls.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2020 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

from django.conf.urls import url

from . import views

urlpatterns = (
    url(r"^$", views.home, name='home'),
    url(r"^dev-guide/$", views.dev_guide),
    url(r"^contact/$", views.contact),
    url(r'^data/$', views.data, name='data'),
    url(r'^log_search/$', views.log_search, name='log_search'),
    url(r'^log_result/$', views.log_result, name='log_result'),
    url(r'^trouble_police/$', views.trouble_police, name='trouble_police'),
    url(r'^monitor_health/$', views.monitor_health, name='monitor_health'),
    url(r'esxi_data/$', views.get_esxi_data, name='esxi_data')



)

urls.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2020 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^account/", include("blueapps.account.urls")),

    # 如果你习惯使用 Django 模板，请在 home_application 里开发你的应用，
    # 这里的 home_application 可以改成你想要的名字
    url(r"^", include(("home_application.urls", 'home_application'), namespace='index')),

    # 如果你习惯使用 mako 模板，请在 mako_application 里开发你的应用，
    # 这里的 mako_application 可以改成你想要的名字
    url(r"^mako/", include("mako_application.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
]

home_application/models.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2020 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

from django.db import models

# Create your models here.
#
#
from datetime import datetime


class BaseModel(models.Model):
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    # 将BaseModel抽象成一个基类
    class Meta:
        abstract = True


class Esix(BaseModel):
    name = models.CharField(max_length=50, verbose_name='asix名')
    cpuMhz = models.CharField(max_length=10, verbose_name='cpu频率(MHZ)')
    cpuUsagePercent = models.CharField(max_length=5, verbose_name='cpu使用率(%)')
    maxMemory = models.CharField(max_length=10, verbose_name='内存最大值(GB)')
    memoryUsage = models.CharField(max_length=10, verbose_name='内存使用(GB)')
    memoryUsagePercent = models.CharField(max_length=5, verbose_name='内存使用率(%)')
    numCpuCores = models.CharField(max_length=3, verbose_name='cpu的核数')
    numCpuPkgs = models.CharField(max_length=3, verbose_name='cpu处理器数量')
    storage_percent = models.CharField(max_length=6, verbose_name='磁盘的使用率')

    def __str__(self):
        return self.name


class EsixVm(BaseModel):
    esixName = models.ForeignKey(Esix, on_delete=models.CASCADE, verbose_name='asix名', null=True, blank=True)
    vmName = models.CharField(max_length=50, verbose_name='虚拟机名',)
    maxVmCpuUsage = models.CharField(max_length=10, verbose_name='cpu最大值(MHZ)')
    numCpu = models.CharField(max_length=3, verbose_name='cpu的核数')
    storage_percent = models.CharField(max_length=6, verbose_name='磁盘使用率(%)')
    vmCpuDemand = models.CharField(max_length=5, verbose_name='cpuDemand')
    vmCpuUsage = models.CharField(max_length=5, verbose_name='cpu使用(MHZ)')
    vmCpuUsagePercent = models.CharField(max_length=6, verbose_name='cpu使用率(%)')
    vmMemoryUsage = models.CharField(max_length=10, verbose_name='内存使用(MHZ)')
    vmMemoryUsagePercent = models.CharField(max_length=6, verbose_name='内存使用率(%)')

    def __str__(self):
        return self.vmName

home_application/views.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2020 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

from django.shortcuts import render, HttpResponse
import json

from home_application.models import Esix, EsixVm
from home_application.utils.pyvmomi_monitor import save_esxi_data

import time
import requests
import sys


# 开发框架中通过中间件默认是需要登录态的，如有不需要登录的，可添加装饰器login_exempt
# 装饰器引入 from blueapps.account.decorators import login_exempt
def home(request):
    """
    首页
    """
    return render(request, "home_application/monitor_line.html")


def log_search(request):
    """
    日志搜索
    """
    return render(request, 'home_application/log_index.html')


def log_result(request):
    """
    日志搜索结果
    """
    return render(request, 'home_application/log_result.html')


def trouble_police(request):
    """
    故障预警
    """
    return render(request, 'home_application/monitor_police.html')


def monitor_health(request):
    """
    数据健康度
    """
    return render(request, 'home_application/monitor_health.html')


def get_esxi_data(request):
    """
    获取esxi数据
    """
    save_esxi_data()
    return HttpResponse('...')


def data(request):
    """
    获取数据
    """
    data_test = {
        "code": 0,
        "result": True,
        "messge": "success",
        "data": {
            "xAxis": ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
            "series": [
                {
                    "name": "磁盘数据",
                    "type": "line",
                    "data": [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
                },
                {
                    "name": "cpu使用",
                    "type": "line",
                    "data": [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
                },
                {
                    "name": "net数据",
                    "type": "line",
                    "data": [1, 5, 9.0, 22.4, 25.7, 12, 175.6, 179, 36, 25, 26, 25]
                }
            ]
        }
    }
    return HttpResponse(json.dumps(data_test, ensure_ascii=False))


def dev_guide(request):
    """
    开发指引
    """
    return render(request, "home_application/dev_guide.html")


def contact(request):
    """
    联系页
    """
    return render(request, "home_application/contact.html")

home_application/templates/home_application/monitor_line.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- 若您需要使用Kendo UI Professional，请联系版权人获得合法的授权或许可。 -->
    <!-- Bootstrap css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <!-- kendo ui css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.common.min.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.default.min.css" rel="stylesheet">
    <!-- font-awesome -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.css" rel="stylesheet">
    <!--蓝鲸提供的公用样式库 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk_pack.css" rel="stylesheet">
    <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <!-- 包括所有kendoui的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/js/kendo.all.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/bk/js/bk.js"></script>
    <!-- 数据埋点统计 -->
    <script src="http://magicbox.bk.tencent.com/static_api/analysis.js"></script>
    <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
    <!--[if lt IE 9]><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/html5shiv.min.js"></script><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/respond.min.js"></script><![endif]-->
</head>

<body class="bg-white" data-bg-color="bg-white">
    <div class="king-page-box">
        <div class="king-container clearfix">
            <nav>
                <div class="king-header2 navbar navbar-blue  f14">
                    <div class="nav-container">
                        <div class="navbar-header">
                            <button class="pull-right visible-xs navbar-toggle collapsed navbar-toggle-sm" type="button" data-toggle="collapse" data-target="#king-header2-navbar-collapse"> <i class="fa fa-fw fa-ellipsis-v">                    </i> </button>
                            <a class="navbar-brand" href="javascript:;" title="故障预警系统">
                                <img src="https://magicbox.bk.tencent.com/static_api/v3/bk/images/logo.png" alt="" class="logo" style="margin-top:-5px;"> </a>
                        </div>
                        <div class="navbar-collapse collapse" id="king-header2-navbar-collapse">
                            <ul class="nav navbar-nav navbar-left hidden-sm">
                                <li class="open">
                                    <a href="{% url 'index:home' %}">
                                        <span>项目信息</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'index:trouble_police' %}">
                                        <span>故障预警</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <span>关键词</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'index:log_search' %}">
                                        <span>数据查询</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'index:monitor_health' %}">
                                        <span>数据健康度</span>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-cog">                            </i>
                                        <span class="ml10"> 管理配置 </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)">
                                        <span> admin </span>
                                        <span class="avatar">
                                            <img src="https://magicbox.bk.tencent.com/static_api/v3/components/horizontal_nav9/images/avatar.jpg"> </span>
                                    </a>
                                </li>
                                <li> <a href="javascript:void(0)">                            退出                        </a> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="container-fluid mb0 ">
                <div class="row">
                    <div class="col-md-4">
                        <div style="height: 300px; -webkit-tap-highlight-color: transparent; user-select: none; background-color: rgba(0, 0, 0, 0); cursor: default;" id="chart_1623832313979" class="king-chart-box chart-area " _echarts_instance_="1623829882048"></div>
                    </div>
                    <div class="col-md-4">
                        <div style="height: 300px; -webkit-tap-highlight-color: transparent; user-select: none; background-color: rgba(0, 0, 0, 0); cursor: default;" id="chart_1623832316423" class="king-chart-box chart-area " _echarts_instance_="1623829882049"></div>
                    </div>
                    <div class="col-md-4">
                        <div style="height: 300px; -webkit-tap-highlight-color: transparent; user-select: none; background-color: rgba(0, 0, 0, 0); cursor: default;" id="chart_1623832318241" class="king-chart-box chart-area " _echarts_instance_="1623829882050"></div>
                    </div>
                </div>
            </div>
            <div class="container-fluid mb0 ">
                <div class="row">
                    <div class="col-md-4">
                        <div style="height: 300px; position: relative;" id="chart_1623832295069" class="king-chart-box chart-line  k-chart" data-role="chart"></div>
                    </div>
                    <div class="col-md-4">
                        <div style="height: 300px; position: relative;" id="chart_1623832308051" class="king-chart-box chart-line  k-chart" data-role="chart"></div>
                    </div>
                    <div class="col-md-4">
                        <div style="height: 300px; position: relative;" id="chart_1623832311278" class="king-chart-box chart-line  k-chart" data-role="chart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--    折线图样式1-->
    <script>
        function createEStandLineChart(conf){
            var myChart = echarts.init(document.getElementById(conf.selector));
            var legendData = []
            for(var i=0; i < conf.data.series.length;i++){
                legendData.push(conf.data.series[i].name)
            }
            myChart.setOption({
                tooltip : {
                    trigger: 'axis'
                },
                legend: {
                    y: 'bottom',
                    data:legendData
                },
                toolbox: {
                    show : true,
                    feature : {
                        mark : {show: true},
                        dataView : {show: true, readOnly: false},
                        magicType : {show: true, type: ['bar','line']},
                        restore : {show: true},
                        saveAsImage : {show: true}
                    }
                },
                calculable : true,
                xAxis : [
                    {
                        type : 'category',
                        data : conf.data.xAxis
                    }
                ],
                yAxis : [
                    {
                        type : 'value',
                        splitArea : {show : true}
                    }
                ],
                series : conf.data.series
            });
         }
        function initEStandLineChart(conf){
            $.ajax({
                url: conf.url,
                type: 'GET',
                dataType: conf.dataType,
                success: function(res){
                    //获取数据成功
                    if (res.result){
                        createEStandLineChart({
                            selector: conf.containerId, // 图表容器
                            data: res.data, // 图表数据
                        });
                    }
                }
            })
        }
    </script>
    <script>
        $(function(){
            initEStandLineChart({
                url: 'http://dev.paas.bk.com:8000/data/',
                dataType: 'json',
                containerId: 'chart_1623832313979'
            });
        });
    </script>
    <script>
        $(function(){
            initEStandLineChart({
                url: 'http://dev.paas.bk.com:8000/data/',
                dataType: 'json',
                containerId: 'chart_1623832316423'
            });
        });
    </script>
    <script>
        $(function(){
            initEStandLineChart({
                url: 'http://dev.paas.bk.com:8000/data/',
                dataType: 'json',
                containerId: 'chart_1623832318241'
            });
        });
    </script>

<!--    折线图样式2-->
    <script>
        // 创建图表
        function createKendoLineChart(conf){
            $(conf.selector).kendoChart({
                transitions: false,
                legend: {
                   position: "bottom"
                },
                colors: ['yellow'],
                theme : 'bootstrap',
                seriesDefaults: {
                    type: 'line',
                    style: "smooth",
                    markers: {
                        visible: false
                    }
                },
                series: conf.data.series,
                categoryAxis: {
                    majorGridLines : {
                        visible: false
                    },
                    categories: conf.data.categories,
                    labels: {
                        rotation: "auto"
                    }
                },
                tooltip: {
                    visible: true,
                    template: "#= category # #= value #"
                }
            });
            //重新绘制
            $(window).on('resize',function(){
                var chart = $(conf.selector).data("kendoChart");
                chart.redraw();
            });
        }

        function initKendoLineChart(conf){
            // 异步请求后台数据
            $.ajax({
                url: conf.url,
                type: 'GET',
                dataType: conf.dataType,
                success: function(res){
                    //获取数据成功
                    if (res.result){
                        var data = {
                            series: res.data.series,
                            categories: res.data.categories
                        };
                        createKendoLineChart({
                            selector: conf.container, // 图表容器
                            data: data // 图表数据
                        });
                    }
                }
            });
        }
    </script>
    <script>
        $(function(){
            initKendoLineChart({
                url: 'https://magicbox.bk.tencent.com/static_api/v3/components/charts_line/demo.json',
                dataType: 'json',
                container: '#chart_1623832295069'
            });
        });
    </script>
    <script>
        $(function(){
            initKendoLineChart({
                url: 'https://magicbox.bk.tencent.com/static_api/v3/components/charts_line/demo.json',
                dataType: 'json',
                container: '#chart_1623832308051'
            });
        });
    </script>
    <script>
        $(function(){
            initKendoLineChart({
                url: 'https://magicbox.bk.tencent.com/static_api/v3/components/charts_line/demo.json',
                dataType: 'json',
                container: '#chart_1623832311278'
            });
        });
    </script>
</body>

</html>

home_application/templates/home_application/monitor_police.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- 若您需要使用Kendo UI Professional，请联系版权人获得合法的授权或许可。 -->
    <!-- Bootstrap css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <!-- kendo ui css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.common.min.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.default.min.css" rel="stylesheet">
    <!-- font-awesome -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.css" rel="stylesheet">
    <!--蓝鲸提供的公用样式库 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk_pack.css" rel="stylesheet">
    <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <!-- 包括所有kendoui的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/js/kendo.all.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/bk/js/bk.js"></script>
    <!-- 数据埋点统计 -->
    <script src="http://magicbox.bk.tencent.com/static_api/analysis.js"></script>
    <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
    <!--[if lt IE 9]><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/html5shiv.min.js"></script><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/respond.min.js"></script><![endif]-->
</head>

<body class="bg-white" data-bg-color="bg-white">
    <div class="king-page-box">
        <div class="king-container clearfix">
            <nav>
                <div class="king-header2 navbar navbar-blue  f14">
                    <div class="nav-container">
                        <div class="navbar-header">
                            <button class="pull-right visible-xs navbar-toggle collapsed navbar-toggle-sm" type="button" data-toggle="collapse" data-target="#king-header2-navbar-collapse"> <i class="fa fa-fw fa-ellipsis-v">                    </i> </button>
                            <a class="navbar-brand" href="javascript:;" title="故障预警系统">
                                <img src="https://magicbox.bk.tencent.com/static_api/v3/bk/images/logo.png" alt="" class="logo" style="margin-top:-5px;"> </a>
                        </div>
                        <div class="navbar-collapse collapse" id="king-header2-navbar-collapse">
                            <ul class="nav navbar-nav navbar-left hidden-sm">
                                <li class="open">
                                    <a href="{% url 'index:home' %}">
                                        <span>项目信息</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'index:trouble_police' %}">
                                        <span>故障预警</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <span>关键词</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'index:log_search' %}">
                                        <span>数据查询</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'index:monitor_health' %}">
                                        <span>数据健康度</span>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-cog">                            </i>
                                        <span class="ml10"> 管理配置 </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)">
                                        <span> admin </span>
                                        <span class="avatar">
                                            <img src="https://magicbox.bk.tencent.com/static_api/v3/components/horizontal_nav9/images/avatar.jpg"> </span>
                                    </a>
                                </li>
                                <li> <a href="javascript:void(0)">                            退出                        </a> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            <table class="table mb0 pr15 ranger-box ">
                <thead>
                    <tr>
                        <th style="width: 100px;">#</th>
                        <th style="width: 20%;">任务</th>
                        <th style="width: 20%;">进度</th>
                        <th style="width: 20%;">开发者</th>
                        <th>结束时间</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 100px;">1</td>
                        <td style="width: 20%;">版本更新</td>
                        <td style="width: 20%;">完成</td>
                        <td style="width: 20%;">管理员</td>
                        <td>2015-09-20</td>
                    </tr>
                    <tr>
                        <td style="width: 100px;">2</td>
                        <td style="width: 20%;">数据备份</td>
                        <td style="width: 20%;">完成</td>
                        <td style="width: 20%;">管理员</td>
                        <td>2015-09-20</td>
                    </tr>
                    <tr>
                        <td style="width: 100px;">3</td>
                        <td style="width: 20%;">定时任务</td>
                        <td style="width: 20%;">完成</td>
                        <td style="width: 20%;">管理员</td>
                        <td>2015-09-20</td>
                    </tr>
                    <tr>
                        <td style="width: 100px;">4</td>
                        <td style="width: 20%;">修复bug</td>
                        <td style="width: 20%;">完成</td>
                        <td style="width: 20%;">管理员</td>
                        <td>2015-09-20</td>
                    </tr>
                </tbody>
            </table>
            <!-- 设置面板Start -->
            <template id="header_tpl_1623833758885">
                <tr>
                    <th style="width: 100px;">#index#</th>
                    <th style="width: 20%;">#task#</th>
                    <th style="width: 20%;">#progress#</th>
                    <th style="width: 20%;">#host#</th>
                    <th>#date#</th>
                </tr>
            </template>
            <template id="tpl_1623833758885">
                <tr>
                    <td style="width: 100px;">#index#</td>
                    <td style="width: 20%;">#columnName1#</td>
                    <td style="width: 20%;">#columnName2#</td>
                    <td style="width: 20%;">#columnName3#</td>
                    <td>#columnName4#</td>
                </tr>
            </template>
            <!-- 设置面板End -->
        </div>
    </div>
    <script>
        $(function(){
                function renderTpl(str, cfg) {
                    var re = /(#(.+?)#)/g;

                    return str.replace(re, function() {
                        var val = cfg[arguments[2]]+'';
                        if(typeof val == 'undefined') {
                            val = '';
                        }
                        return val;
                    });
                }

                // 异步请求后台数据
                $.ajax({
                    url: 'https://magicbox.bk.tencent.com/static_api/v3/components/table6/data.json',
                    type: 'GET',
                    success: function(res){
                        var _html = ' ';
                        var list = res.items;
                        var tpl = $('#tpl_1623833758885').html();
                        var headerTpl =  $('#header_tpl_1623833758885').html();
                        for (var i=0,len=list.length; i < len; i++){
                            var item = list[i];
                            _html += renderTpl(tpl, item)
                        }
                        $('#code_1623833758885 tbody').html(_html);
                        $('.ranger-box thead').html(renderTpl(headerTpl,res.catalogues));
                    }
                });
            });
    </script>
</body>

</html>